"""fix #1

Revision ID: 0f3fb76b07c6
Revises: c9e43b37f53a
Create Date: 2025-10-17 23:31:36.897461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3fb76b07c6'
down_revision: Union[str, Sequence[str], None] = 'c9e43b37f53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'users', ['address_id'], ['id'])
    # ### end Alembic commands ###
