"""fix #3

Revision ID: 3d3743493f48
Revises: fc331ea431c7
Create Date: 2025-10-17 23:46:50.341360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3743493f48'
down_revision: Union[str, Sequence[str], None] = 'fc331ea431c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
