"""fix #4

Revision ID: 43cc65b97f2c
Revises: 3d3743493f48
Create Date: 2025-10-17 23:47:09.612193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cc65b97f2c'
down_revision: Union[str, Sequence[str], None] = '3d3743493f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
